# Generated by Django 3.2.13 on 2022-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_resume_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.IntegerField(choices=[(0, 'Education'), (1, 'Experience'), (2, 'Skills'), (3, 'Awards')]),
        ),
    ]
