# Generated by Django 3.2.13 on 2022-04-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_resume_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_finish', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('academy', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon')),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=202, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('last_month', models.IntegerField(blank=True, null=True)),
                ('last_week', models.IntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start_finish',
        ),
        migrations.AlterField(
            model_name='about',
            name='live',
            field=models.CharField(max_length=202),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=202),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=202),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(max_length=202),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.resume'),
        ),
    ]
